### ISSUE TITLE
dig on nested object returns undefined method '[]'

### ISSUE THREAD

**Issue by jbowles** [hopsoft/goldmine#1]
I've a large serialized object with nested hashes and arrays. It seems that if I dig too deep I get a problem. I'll post an example of the serialization at the very bottom.
## Here is how to reproduce:

``` ruby
onovate = list1.dig("onovate"){|i| i["entities"]["hashtags"][0]['text']}
```

Notice that I can do this

``` ruby
list1[0]["entities"]["hashtags"][0]['text']
     #returns => "onovate"
```

Here is the full error message:

``` ruby
NoMethodError: undefined method `[]' for nil:NilClass
    from (irb):87:in `block in irb_binding'
    from /Users/jbowles/.rvm/gems/ruby-1.9.3-p0/gems/goldmine-0.0.3/lib/goldmine.rb:7:in `block in dig'
    from /Users/jbowles/.rvm/gems/ruby-1.9.3-p0/gems/goldmine-0.0.3/lib/goldmine.rb:6:in `each'
    from /Users/jbowles/.rvm/gems/ruby-1.9.3-p0/gems/goldmine-0.0.3/lib/goldmine.rb:6:in `reduce'
    from /Users/jbowles/.rvm/gems/ruby-1.9.3-p0/gems/goldmine-0.0.3/lib/goldmine.rb:6:in `dig'
    from (irb):87
    from /Users/jbowles/.rvm/rubies/ruby-1.9.3-p0/bin/irb:16:in `<main>'
```
## Here is the serialization

``` ruby
{"entities"=>{"media"=>[{"type"=>"photo", "media_url_https"=>"https://p.twimg.com/Aupzj0dCMAAcqo9.jpg", "indices"=>[54, 74], "expanded_url"=>"http://twitter.com/bowleslingjw/status/210107391830798337/photo/1", "sizes"=>{"small"=>{"resize"=>"fit", "h"=>241, "w"=>340}, "medium"=>{"resize"=>"fit", "h"=>248, "w"=>350}, "large"=>{"resize"=>"fit", "h"=>248, "w"=>350}, "thumb"=>{"resize"=>"crop", "h"=>150, "w"=>150}}, "id_str"=>"210107391839186944", "url"=>"http://t.co/RWz19zTG", "media_url"=>"http://p.twimg.com/Aupzj0dCMAAcqo9.jpg", "display_url"=>"pic.twitter.com/RWz19zTG", "id"=>210107391839186944}], "urls"=>[], "hashtags"=>[{"text"=>"onovate", "indices"=>[45, 53]}], "user_mentions"=>[]}, "favorited"=>false, "text"=>"next bbq for it with grill made for grillin' #onovate http://t.co/RWz19zTG", "in_reply_to_user_id_str"=>nil, "place"=>nil, "truncated"=>false, "in_reply_to_screen_name"=>nil, "source"=>"web", "created_at"=>"Tue Jun 05 20:34:40 +0000 2012", "id_str"=>"210107391830798337", "in_reply_to_user_id"=>nil, "possibly_sensitive_editable"=>true, "coordinates"=>nil, "geo"=>nil, "retweeted"=>false, "contributors"=>nil, "retweet_count"=>0, "possibly_sensitive"=>false, "user"=>{"follow_request_sent"=>nil, "lang"=>"en", "notifications"=>nil, "profile_sidebar_border_color"=>"eeeeee", "screen_name"=>"bowleslingjw", "default_profile"=>false, "time_zone"=>"Mountain Time (US & Canada)", "is_translator"=>false, "show_all_inline_media"=>false, "profile_use_background_image"=>true, "following"=>nil, "profile_background_image_url_https"=>"https://si0.twimg.com/images/themes/theme14/bg.gif", "friends_count"=>92, "profile_text_color"=>"333333", "description"=>"Computer. Linguist. I am doing something with languages or computers. ", "profile_background_image_url"=>"http://a0.twimg.com/images/themes/theme14/bg.gif", "created_at"=>"Thu May 12 17:05:07 +0000 2011", "id_str"=>"297521078", "default_profile_image"=>false, "statuses_count"=>120, "profile_link_color"=>"009999", "url"=>"http://jbowles.github.com", "verified"=>false, "favourites_count"=>1, "followers_count"=>19, "profile_image_url_https"=>"https://si0.twimg.com/profile_images/2153871973/9608da7db688950cfd161f51feb648ba_normal.jpeg", "profile_image_url"=>"http://a0.twimg.com/profile_images/2153871973/9608da7db688950cfd161f51feb648ba_normal.jpeg", "profile_background_color"=>"131516", "protected"=>false, "profile_background_tile"=>true, "location"=>"Eagle Mountain", "name"=>"josh bowles", "profile_sidebar_fill_color"=>"efefef", "id"=>297521078, "listed_count"=>2, "contributors_enabled"=>false, "geo_enabled"=>false, "utc_offset"=>-25200}, "id"=>210107391830798337, "in_reply_to_status_id_str"=>nil, "in_reply_to_status_id"=>nil} 
```

**Comment by hopsoft** [comment]
The API has changed quite a bit since this was filed. I'm going to mark this resolved for now.
